POS/Areas/Admin/Controllers/BrandController.cs
using Microsoft.AspNet.Identity;
using POS.Service.IService;
using POS.ViewModel.Brand;
using System;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace POS.Areas.Admin.Controllers
{
    public class BrandController : Controller
    {
        private readonly IBrandService _brandService;

        public BrandController(IBrandService BrandService)
        {
            this._brandService = BrandService;
        }
        public BrandController()
        {

        }
        // GET: Admin/Brand
        public async Task<ActionResult> Index()
        {
            return View(await this._brandService.GetAll());
        }

        // GET: Admin/Brand/Details/5
        public async Task<ActionResult> Details(int id)
        {
            return View(await this._brandService.GetById(id));
        }

        // GET: Admin/Brand/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/Brand/Create
        [HttpPost]
        public async Task<ActionResult> Create(HttpPostedFileBase file, BrandViewModel viewModel)
        {
            if (file.ContentType == "image/jpg" || file.ContentType == "image/jpeg" || file.ContentType == "image/png" || file.ContentType == "image/gif")
            {
                string fileName = Path.GetFileName(viewModel.Name + "-" + DateTime.Now.ToString("ddmmyyyyfff")) + Path.GetExtension(file.FileName);
                string path = Path.Combine(Server.MapPath("/Data/Images/Brand"), fileName);
                file.SaveAs(path);
                viewModel.ImagePath = "/Data/Images/Brand/" + fileName;
            }

            viewModel.DateCreated = DateTime.Now;
            viewModel.DateUpdated = DateTime.Now;
            viewModel.CreatedByUserId = User.Identity.GetUserId();
            viewModel.UpdatedByUserId = User.Identity.GetUserId();
            viewModel.IsActive = true;
            try
            {
                // TODO: Add insert logic here
                await this._brandService.Insert(viewModel);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                throw ex;
            }

        }

        // GET: Admin/Brand/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            //if (id == null)
            //{
            //    return ();
            //}
            var brand = await this._brandService.GetById(id);
            //if (file == null)
            //{
            //    return NotFound();
            //}

            return View(brand);

        }

        // POST: Admin/Brand/Edit/5
        [HttpPost]
        public async Task<ActionResult> Edit(int id, BrandViewModel viewModel, HttpPostedFileBase file)
        {
            //if (id != viewModel.Id)
            //{
            //    return NotFound();
            //}
            if(file !=null)
            {
                if (file.ContentType == "image/jpg" || file.ContentType == "image/jpeg" || file.ContentType == "image/png" || file.ContentType == "image/gif")
                {
                    string fileName = Path.GetFileName(viewModel.Name + "-" + DateTime.Now.ToString("ddmmyyyyfff")) + Path.GetExtension(file.FileName);
                    string path = Path.Combine(Server.MapPath("/Data/Images/Brand"), fileName);
                    file.SaveAs(path);
                    viewModel.ImagePath = "/Data/Images/Brand/" + fileName;
                }
            }

            viewModel.DateCreated = DateTime.Now;
            viewModel.DateUpdated = DateTime.Now;
            viewModel.CreatedByUserId = User.Identity.GetUserId();
            viewModel.UpdatedByUserId = User.Identity.GetUserId();
            viewModel.IsActive = true;
            try
            {
                await this._brandService.Update(viewModel);
                return RedirectToAction(nameof(Index));
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!FileExists(viewModel.Id))
                {
                    //return NotFound();
                }
                else
                {
                    throw;
                }
            }


            return View(viewModel);
        }

        private  bool FileExists(int id)
        {
            return  this._brandService.GetAll().Result.Any(x => x.Id == id);
        }
        // GET: Admin/Brand/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            //if (id == null)
            //{
            //    return NotFound();
            //}
            var brand = await this._brandService.GetById(id);
            //if (file == null)
            //{
            //    return NotFound();
            //}
            return View(brand);
        }

        // POST: Admin/Brand/Delete/5
        [HttpPost]
        public async Task<ActionResult> Delete(int id, BrandViewModel viewModel)
        {
            await this._brandService.Delete(id);
            return RedirectToAction(nameof(Index));
        }


    }
}

POS/Controllers/BrandController.cs
using Microsoft.AspNet.Identity;
using POS.Service.IService;
using POS.ViewModel.Brand;
using System;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace POS.Controllers
{
    public class BrandController : Controller
    {
        private readonly IBrandService _brandService;

        public BrandController(IBrandService BrandService)
        {
            this._brandService = BrandService;
        }
        public BrandController()
        {

        }
        // GET: Admin/Brand
        public async Task<ActionResult> Index()
        {
            return View(await this._brandService.GetAll());
        }

        // GET: Admin/Brand/Details/5
        public async Task<ActionResult> Details(int id)
        {
            return View(await this._brandService.GetById(id));
        }

        // GET: Admin/Brand/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/Brand/Create
        [HttpPost]
        public async Task<ActionResult> Create(HttpPostedFileBase file, BrandViewModel viewModel)
        {
            if (file.ContentType == "image/jpg" || file.ContentType == "image/jpeg" || file.ContentType == "image/png" || file.ContentType == "image/gif")
            {
                string fileName = Path.GetFileName(viewModel.Name + "-" + DateTime.Now.ToString("ddmmyyyyfff")) + Path.GetExtension(file.FileName);
                string path = Path.Combine(Server.MapPath("/Data/Images/Brand"), fileName);
                file.SaveAs(path);
                viewModel.ImagePath = "/Data/Images/Brand/" + fileName;
            }

            viewModel.DateCreated = DateTime.Now;
            viewModel.DateUpdated = DateTime.Now;
            viewModel.CreatedByUserId = User.Identity.GetUserId();
            viewModel.UpdatedByUserId = User.Identity.GetUserId();
            viewModel.IsActive = true;
            try
            {
                // TODO: Add insert logic here
                await this._brandService.Insert(viewModel);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                throw ex;
            }

        }

        // GET: Admin/Brand/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            //if (id == null)
            //{
            //    return ();
            //}
            var brand = await this._brandService.GetById(id);
            //if (file == null)
            //{
            //    return NotFound();
            //}

            return View(brand);

        }

        // POST: Admin/Brand/Edit/5
        [HttpPost]
        public async Task<ActionResult> Edit(int id, BrandViewModel viewModel, HttpPostedFileBase file)
        {
            //if (id != viewModel.Id)
            //{
            //    return NotFound();
            //}
            if(file !=null)
            {
                if (file.ContentType == "image/jpg" || file.ContentType == "image/jpeg" || file.ContentType == "image/png" || file.ContentType == "image/gif")
                {
                    string fileName = Path.GetFileName(viewModel.Name + "-" + DateTime.Now.ToString("ddmmyyyyfff")) + Path.GetExtension(file.FileName);
                    string path = Path.Combine(Server.MapPath("/Data/Images/Brand"), fileName);
                    file.SaveAs(path);
                    viewModel.ImagePath = "/Data/Images/Brand/" + fileName;
                }
            }

            viewModel.DateCreated = DateTime.Now;
            viewModel.DateUpdated = DateTime.Now;
            viewModel.CreatedByUserId = User.Identity.GetUserId();
            viewModel.UpdatedByUserId = User.Identity.GetUserId();
            viewModel.IsActive = true;
            try
            {
                await this._brandService.Update(viewModel);
                return RedirectToAction(nameof(Index));
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!FileExists(viewModel.Id))
                {
                    //return NotFound();
                }
                else
                {
                    throw;
                }
            }


            return View(viewModel);
        }

        private  bool FileExists(int id)
        {
            return  this._brandService.GetAll().Result.Any(x => x.Id == id);
        }
        // GET: Admin/Brand/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            //if (id == null)
            //{
            //    return NotFound();
            //}
            var brand = await this._brandService.GetById(id);
            //if (file == null)
            //{
            //    return NotFound();
            //}
            return View(brand);
        }

        // POST: Admin/Brand/Delete/5
        [HttpPost]
        public async Task<ActionResult> Delete(int id, BrandViewModel viewModel)
        {
            await this._brandService.Delete(id);
            return RedirectToAction(nameof(Index));
        }


    }
}

POS/Views/Brand/Create.cshtml
@model POS.ViewModel.Brand.BrandViewModel

@{
    ViewBag.Title = "Create";
    var role = User.IsInRole("Super Admin");
    if (role == true)
    {
        Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    }
    else
    {
        Layout = "~/Views/Shared/_Layout.cshtml";
    }
}
    
<!--begin::Content-->
<div class="content d-flex flex-column flex-column-fluid" id="kt_content">
    <!--begin::Subheader-->
    <div class="subheader py-2 py-lg-6 subheader-solid" id="kt_subheader">
        <div class="container-fluid d-flex align-items-center justify-content-between flex-wrap flex-sm-nowrap">
            <!--begin::Info-->
            <div class="d-flex align-items-center flex-wrap mr-1">
                <!--begin::Page Heading-->
                <div class="d-flex align-items-baseline flex-wrap mr-5">
                    <!--begin::Page Title-->
                    <h5 class="text-dark font-weight-bold my-1 mr-5">Dashboard</h5>
                    <!--end::Page Title-->
                    <!--begin::Breadcrumb-->
                    <ul class="breadcrumb breadcrumb-transparent breadcrumb-dot font-weight-bold p-0 my-2 font-size-sm">
                        <li class="breadcrumb-item">
                            <a href="" class="text-muted">Brand</a>
                        </li>
                        <li class="breadcrumb-item">
                            <a href="" class="text-muted">Add Brand</a>
                        </li>
                    </ul>
                    <!--end::Breadcrumb-->
                </div>
                <!--end::Page Heading-->
            </div>
            <!--end::Info-->
        </div>
    </div>
    <!--end::Subheader-->
    <!--begin::Entry-->
    <div class="d-flex flex-column-fluid">
        <!--begin::Container-->
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <!--begin::Card-->
                    <div class="card card-custom gutter-b example example-compact">
                        <div class="card-header flex-wrap py-5">
                            <div class="card-title">
                                <h3 class="card-label">
                                    Brand
                                </h3>
                            </div>
                            <div class="card-toolbar">
                                <!--begin::Button-->
                                <a href="@Url.Action("Index", "Brand", new { area=""})" class="btn btn-primary font-weight-bolder">
                                    <span class="svg-icon svg-icon-md">
                                        <!--begin::Svg Icon | Flatten.svg-->
                                        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px"
                                             height="24px" viewBox="0 0 24 24" version="1.1">
                                            <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                                <rect x="0" y="0" width="24" height="24"></rect>
                                                <path d="M10,4 L21,4 C21.5522847,4 22,4.44771525 22,5 L22,7 C22,7.55228475 21.5522847,8 21,8 L10,8 C9.44771525,8 9,7.55228475 9,7 L9,5 C9,4.44771525 9.44771525,4 10,4 Z M10,10 L21,10 C21.5522847,10 22,10.4477153 22,11 L22,13 C22,13.5522847 21.5522847,14 21,14 L10,14 C9.44771525,14 9,13.5522847 9,13 L9,11 C9,10.4477153 9.44771525,10 10,10 Z M10,16 L21,16 C21.5522847,16 22,16.4477153 22,17 L22,19 C22,19.5522847 21.5522847,20 21,20 L10,20 C9.44771525,20 9,19.5522847 9,19 L9,17 C9,16.4477153 9.44771525,16 10,16 Z"
                                                      fill="#000000"></path>
                                                <rect fill="#000000" opacity="0.3" x="2" y="4" width="5" height="16" rx="1"></rect>
                                            </g>
                                        </svg>
                                        <!--end::Svg Icon-->
                                    </span>Back to List
                                </a>
                                <!--end::Button-->
                            </div>
                        </div>
                        @using (Html.BeginForm("Create", "Brand", FormMethod.Post, new { enctype = "multipart/form-data" }))
                        {
                            @Html.AntiForgeryToken()
                            <div class="card-body">
                                <div class="row py-8 px-8 py-md-10 px-md-0">
                                    <div class="col-md-6">
                                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                                        <div class="form-group">
                                            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-12" })
                                            <div class="col-md-12">
                                                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", placeholder = "Enter brand name" } })
                                                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-12" })
                                            <div class="col-md-12">
                                                @Html.TextAreaFor(model => model.Description, new { @class = "form-control", rows = "3", placeholder = "Enter description" })
                                                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                                            </div>
                                        </div>

                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group row">
                                            @Html.LabelFor(model => model.ImagePath, htmlAttributes: new { @class = "col-xl-3 col-lg-3 col-form-label text-right" })
                                            <div class="col-lg-9 col-xl-6">
                                                <div class="image-input image-input-outline" id="kt_image_5" style="background-image: url('../../Content/media/users/blank.png'); ">
                                                    <div class="image-input-wrapper" style="background-image: none;"></div>
                                                    <label class="btn btn-xs btn-icon btn-circle btn-white btn-hover-text-primary btn-shadow" data-action="change" data-toggle="tooltip" title="" data-original-title="Change avatar">
                                                        <i class="fa fa-pen icon-sm text-muted"></i>
                                                        <input type="file" name="file" multiple="multiple" id="file">
                                                        <input type="hidden" name="avatar_remove" value="0">
                                                    </label>
                                                    <span class="btn btn-xs btn-icon btn-circle btn-white btn-hover-text-primary btn-shadow" data-action="cancel" data-toggle="tooltip" title="" data-original-title="Cancel avatar">
                                                        <i class="ki ki-bold-close icon-xs text-muted"></i>
                                                    </span>
                                                    <span class="btn btn-xs btn-icon btn-circle btn-white btn-hover-text-primary btn-shadow" data-action="remove" data-toggle="tooltip" title="" data-original-title="Remove avatar">
                                                        <i class="ki ki-bold-close icon-xs text-muted"></i>
                                                    </span>
                                                </div>
                                                <span class="form-text text-muted">Default empty input with blank image</span>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                            </div>
                            <div class="card-footer">
                                <div class="row">
                                    <div class="col-lg-12">
                                        <button type="submit" class="btn btn-primary mr-2" onclick="InsertAside()">Submit</button>
                                        <button type="reset" class="btn btn-secondary">Cancel</button>
                                    </div>
                                </div>
                            </div>
                        }
                        <!--end::Form-->
                    </div>
                    <!--end::Card-->
                </div>
            </div>
        </div>
        <!--end::Container-->
    </div>
    <!--end::Entry-->
</div>
<!--end::Content-->

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
    <script>
        var avatar = new KTImageInput('kt_image_5');

        avatar.on('cancel', function (imageInput) {
            toastr.success("Image successfully cancel !");
        });

        avatar.on('change', function (imageInput) {
            toastr.success("Image successfully changed !");
        });

        avatar.on('remove', function (imageInput) {
            toastr.danger("Image successfully removed !");
        });
    </script>
}

POS/Views/Brand/Delete.cshtml
@model POS.ViewModel.Brand.BrandViewModel
@{
    ViewBag.Title = "Delete";
    var role = User.IsInRole("Super Admin");
    if (role == true)
    {
        Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    }
    else
    {
        Layout = "~/Views/Shared/_Layout.cshtml";
    }
}

<!--begin::Content-->
<div class="content d-flex flex-column flex-column-fluid" id="kt_content">
    <!--begin::Subheader-->
    <div class="subheader py-2 py-lg-6 subheader-solid" id="kt_subheader">
        <div class="container-fluid d-flex align-items-center justify-content-between flex-wrap flex-sm-nowrap">
            <!--begin::Info-->
            <div class="d-flex align-items-center flex-wrap mr-1">
                <!--begin::Page Heading-->
                <div class="d-flex align-items-baseline flex-wrap mr-5">
                    <!--begin::Page Title-->
                    <h5 class="text-dark font-weight-bold my-1 mr-5">Dashboard</h5>
                    <!--end::Page Title-->
                    <!--begin::Breadcrumb-->
                    <ul class="breadcrumb breadcrumb-transparent breadcrumb-dot font-weight-bold p-0 my-2 font-size-sm">
                        <li class="breadcrumb-item">
                            <a href="" class="text-muted">Brand</a>
                        </li>
                        <li class="breadcrumb-item">
                            <a href="" class="text-muted">Brand Details</a>
                        </li>
                    </ul>
                    <!--end::Breadcrumb-->
                </div>
                <!--end::Page Heading-->
            </div>
            <!--end::Info-->
        </div>
    </div>
    <!--end::Subheader-->
    <!--begin::Entry-->
    <div class="d-flex flex-column-fluid">
        <!--begin::Container-->
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <!--begin::Card-->
                    <div class="card card-custom gutter-b example example-compact">
                        <div class="card-header flex-wrap py-5">
                            <div class="card-title">
                                <h3 class="card-label">
                                    Brand Details
                                </h3>
                            </div>
                            <div class="card-toolbar">
                                <div class="example-tools justify-content-center">
                                    <!--begin::Button-->
                                    <a href="@Url.Action("Edit", "Brand", new { id = Html.ValueFor(model => model.Id), area= ""})" class="btn btn-primary font-weight-bolder mr-5">
                                        <span class="svg-icon svg-icon-warning svg-icon-md">
                                            <!--begin::Svg Icon | path:assets/media/svg/icons/Design/Edit.svg-->
                                            <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1">
                                                <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                                    <rect x="0" y="0" width="24" height="24" />
                                                    <path d="M8,17.9148182 L8,5.96685884 C8,5.56391781 8.16211443,5.17792052 8.44982609,4.89581508 L10.965708,2.42895648 C11.5426798,1.86322723 12.4640974,1.85620921 13.0496196,2.41308426 L15.5337377,4.77566479 C15.8314604,5.0588212 16,5.45170806 16,5.86258077 L16,17.9148182 C16,18.7432453 15.3284271,19.4148182 14.5,19.4148182 L9.5,19.4148182 C8.67157288,19.4148182 8,18.7432453 8,17.9148182 Z" fill="#000000" fill-rule="nonzero" transform="translate(12.000000, 10.707409) rotate(-135.000000) translate(-12.000000, -10.707409) " />
                                                    <rect fill="#000000" opacity="0.3" x="5" y="20" width="15" height="2" rx="1" />
                                                </g>
                                            </svg><!--end::Svg Icon-->
                                        </span>Edit
                                    </a>
                                    <!--end::Button-->
                                    <!--begin::Button-->
                                    <a href="@Url.Action("Index", "Brand")" class="btn btn-primary font-weight-bolder">
                                        <span class="svg-icon svg-icon-md">
                                            <!--begin::Svg Icon | Flatten.svg-->
                                            <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px"
                                                 height="24px" viewBox="0 0 24 24" version="1.1">
                                                <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                                    <rect x="0" y="0" width="24" height="24"></rect>
                                                    <path d="M10,4 L21,4 C21.5522847,4 22,4.44771525 22,5 L22,7 C22,7.55228475 21.5522847,8 21,8 L10,8 C9.44771525,8 9,7.55228475 9,7 L9,5 C9,4.44771525 9.44771525,4 10,4 Z M10,10 L21,10 C21.5522847,10 22,10.4477153 22,11 L22,13 C22,13.5522847 21.5522847,14 21,14 L10,14 C9.44771525,14 9,13.5522847 9,13 L9,11 C9,10.4477153 9.44771525,10 10,10 Z M10,16 L21,16 C21.5522847,16 22,16.4477153 22,17 L22,19 C22,19.5522847 21.5522847,20 21,20 L10,20 C9.44771525,20 9,19.5522847 9,19 L9,17 C9,16.4477153 9.44771525,16 10,16 Z"
                                                          fill="#000000"></path>
                                                    <rect fill="#000000" opacity="0.3" x="2" y="4" width="5" height="16" rx="1"></rect>
                                                </g>
                                            </svg>
                                            <!--end::Svg Icon-->
                                        </span>Back to List
                                    </a>
                                    <!--end::Button-->
                                </div>

                            </div>
                        </div>

                        <!--begin::card body-->
                        <div class="card-body">
                            <!-- begin: Invoice footer-->
                            <div class="row justify-content-center bg-gray-100 py-8 px-8 py-md-10 px-md-0">
                                <div class="col-md-9">
                                    <div class="table-responsive">
                                        <table class="table">
                                            <tbody>
                                                @using (Html.BeginForm())
                                                {
                                                    @Html.AntiForgeryToken()
                                                    <tr class="font-weight-boldest border-bottom-0 font-size-lg">
                                                        <td class="border-top-0 pl-0 py-4" style="width: 15%">@Html.DisplayNameFor(model => model.Name)</td>
                                                        <td class="border-top-0  py-4">@Html.DisplayFor(model => model.Name)</td>
                                                    </tr>
                                                    <tr class="font-weight-boldest border-bottom-0 font-size-lg">
                                                        <td class="border-top-0 pl-0 py-4">@Html.DisplayNameFor(model => model.ImagePath)</td>
                                                        <td class="border-top-0  py-4"> <img src="@Html.ValueFor(model => model.ImagePath)" width="45" height="45" alt="logo" /></td>
                                                    </tr>
                                                    <tr class="font-weight-boldest border-bottom-0 font-size-lg">
                                                        <td class="border-top-0 pl-0 py-4">@Html.DisplayNameFor(model => model.Description)</td>
                                                        <td class="border-top-0  py-4">@Html.DisplayFor(model => model.Description)</td>
                                                    </tr>
                                                    <tr>
                                                        <td><input type="submit" value="Delete" class="btn btn-danger" /></td>
                                                    </tr>
                                                }
                                                </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <!--end::card body-->
                    </div>
                    <!--end::Card-->
                </div>
            </div>
        </div>
        <!--end::Container-->
    </div>
    <!--end::Entry-->
</div>
<!--end::Content-->

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}